### ISSUE TITLE
Someone may have stolen credit for your work

### ISSUE THREAD

**Issue by EdTheLegendary** [suve/rust-on-android#2]
Hey, I wanted to let you know that I think someone tried to pass off your code as their own.
https://github.com/martinwairegi/rustonandroid
To boot, the same guy wrote a crappy "tutorial" based off your work which had been giving me a headache.
https://blog.logrocket.com/integrating-rust-module-android-app/
He didn't outright claim it was his, but it was very heavily implied, combined with the fact that his repository is just a clone of your repository but he ripped the helpful readme you have out.
Anyway, thanks for making this repository :)

**Comment by suve** [comment]
Huh. Well that's a first for me.

I like how the code in the repo probably won't even work because, while the package name is changed inside Java code, the Rust code still uses the original one.

Anyway, glad you've found this repo useful. Maybe I'll look into updating this to the latest NDK one day.
